version: "3.7"

services:
  db:
    image: postgres:14
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    env_file:
      - .dockerenv
      - .env.local_password
  web:
    build:
      context: .
      dockerfile: docker/apiserver/Dockerfile-local
    restart: always
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/kosa
    ports:
      - "3000:3000"
    env_file:
      - .dockerenv
      - .env.local_password
    environment:
      - RUN_INGESTION=yes
    depends_on:
      - db