name: CI
on: push

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    container:
      image: timbru31/ruby-node:latest

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kosa2_ci
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Setup app dependencies
        run: |
          gem install bundler -v 2.4.10 --no-document
          bundle install --jobs 4 --retry 3

#      - name: Install rbenv / Ruby
#        uses: ruby/setup-ruby@v1
#        with:
#          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
#          # Ruby version selected by .ruby-version file (rbenv)

      - name: Setup
        id: setup
        run: |
          {
            echo "RAILS_TEST_ENV=smoke"
          } >> "$GITHUB_OUTPUT"

      - name: Print Setup
        id: print_setup
        run: |
          {
            echo "### Workflow variables"
            echo "| Variable          | Value                                        |"
            echo "| ----------------- | -------------------------------------------- |"
            echo "| RAILS_TEST_ENV    | ${{ steps.setup.outputs.RAILS_TEST_ENV }}    |"
          } >> $GITHUB_STEP_SUMMARY

      - name: Setup database
        env:
          RAILS_ENV: test
          POSTGRES_HOST: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: kosa2_ci
          POSTGRES_PORT: ${{ job.services.postgres.ports[5432] }}
        run: |
          cp config/database.ci.yml config/database.yml
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Smoke Test
        run: bundle exec rails test

#      - name: Build Docker
#        uses: docker/build-push-action@v5
#        with:
#          pull: true # equivalent to --pull, not --pull-always / --pull=always
#          push: false
#          context: .
#          # https://docs.docker.com/build/ci/github-actions/multi-platform/
#          # https://dev.to/cloudx/multi-arch-docker-images-the-easy-way-with-github-actions-4k54
#          platforms: linux/amd64 # ,linux/arm64
#          file: ./Dockerfile
#          build-args: |
#            ENDB_GIT_DESCRIBE=${{ steps.setup.outputs.ENDB_GIT_DESCRIBE }}
#            RUST_OS=${{ steps.setup.outputs.RUST_OS }}
#            SBCL_OS=${{ steps.setup.outputs.SBCL_OS }}
#            ENDB_OS=${{ steps.setup.outputs.ENDB_OS }}
#          tags: ${{ steps.setup.outputs.DOCKER_TAG }} # not required, but maintains
#                                                      # symmetry with build-push-docker.yml
